# Generated by Django 5.0.6 on 2025-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('contribution', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckCardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
