# Generated by Django 5.2 on 2025-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('departmentname', models.TextField(blank=True, db_column='departmentName', null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheckcard',
            fields=[
                ('cardid', models.AutoField(db_column='cardID', primary_key=True, serialize=False)),
                ('cardname', models.TextField(blank=True, db_column='cardName', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, db_column='last_update', null=True)),
            ],
            options={
                'db_table': 'HealthCheckCard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summaryid', models.AutoField(db_column='summaryID', primary_key=True, serialize=False)),
                ('progressstatus', models.TextField(blank=True, db_column='progressStatus', null=True)),
                ('averagevote', models.FloatField(blank=True, db_column='averageVote', null=True)),
            ],
            options={
                'db_table': 'Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='teamID', primary_key=True, serialize=False)),
                ('teamname', models.TextField(blank=True, db_column='teamName', null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=50)),
                ('managerID', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteid', models.AutoField(db_column='voteID', primary_key=True, serialize=False)),
                ('votevalue', models.IntegerField(blank=True, db_column='voteValue', null=True)),
                ('progressstatus', models.TextField(blank=True, db_column='progressStatus', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('votingdate', models.DateField(blank=True, db_column='voting_date', null=True)),
            ],
            options={
                'db_table': 'Vote',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DepartmentPerformance',
        ),
        migrations.DeleteModel(
            name='HealthCheckCardUsage',
        ),
    ]
