# Generated by Django 5.0.6 on 2025-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=50)),
                ('managerID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
