# Generated by Django 5.0.6 on 2025-03-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managerID',
        ),
    ]
