# Generated by Django 5.2 on 2025-04-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('departmentname', models.TextField(blank=True, db_column='departmentName')),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheckcard',
            fields=[
                ('cardid', models.AutoField(db_column='cardID', primary_key=True, serialize=False)),
                ('cardname', models.TextField(blank=True, db_column='cardName', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, db_column='comments', null=True)),
            ],
            options={
                'db_table': 'HealthCheckCard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summaryid', models.AutoField(db_column='summaryID', primary_key=True, serialize=False)),
                ('progressstatus', models.TextField(blank=True, db_column='progressStatus', null=True)),
                ('averagevote', models.FloatField(blank=True, db_column='averageVote', null=True)),
            ],
            options={
                'db_table': 'Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='teamID', primary_key=True, serialize=False)),
                ('teamname', models.TextField(blank=True, db_column='teamName', null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteid', models.AutoField(db_column='voteID', primary_key=True, serialize=False)),
                ('votevalue', models.IntegerField(blank=True, db_column='voteValue', null=True)),
                ('progressstatus', models.TextField(blank=True, db_column='progressStatus', null=True)),
                ('votingdate', models.DateField(blank=True, db_column='voting_date', null=True)),
                ('comments', models.TextField(blank=True, db_column='comments', null=True)),
            ],
            options={
                'db_table': 'Vote',
                'managed': False,
            },
        ),
    ]
