# Generated by Django 5.0.6 on 2025-04-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthcheckcard',
            fields=[
                ('cardid', models.AutoField(db_column='cardID', primary_key=True, serialize=False)),
                ('cardname', models.TextField(blank=True, db_column='cardName', null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HealthCheckCard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='sessionID', primary_key=True, serialize=False)),
                ('sessiondate', models.DateField(blank=True, db_column='sessionDate', null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=50)),
                ('managerID', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteid', models.AutoField(db_column='voteID', primary_key=True, serialize=False)),
                ('votevalue', models.IntegerField(blank=True, db_column='voteValue', null=True)),
                ('progressstatus', models.TextField(blank=True, db_column='progressStatus', null=True)),
            ],
            options={
                'db_table': 'Vote',
                'managed': False,
            },
        ),
    ]
